naver:
  client-id: "네이버 클라이언트 아이디"
  client-secret: "네이버 클라이언트 시크릿"
  book-search-url: "https://openapi.naver.com/v1/search/book.json"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lldj123414
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  port: 8080