spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
naver:
  client-id: 6CryI4ygsAq3XwpGIaBN
  client-secret: ZxazVEi_Dq
  book-search-url: https://openapi.naver.com/v1/search/book.json